[package]
name = "hello-tera"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
salvo = { version = "0.37.7", features = ["affix"] }
tera = "1.17.1"
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"